"""
reporter.py
-----------
Generates a self-contained HTML report for one or multiple processed images.
Includes:
  - RGB composite & False Color Infrared (CIR) images
  - Classification map
  - Interactive spectral plots (Plotly)
  - Per-class statistics table
  - Processing log summary
"""

import base64
import io
import logging
import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

logger = logging.getLogger(__name__)


# ===================================================================
# HTML TEMPLATE
# ===================================================================

_HTML_HEAD = """<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f0f2f5; color: #222; }}
  .container {{ max-width: 1400px; margin: 0 auto; padding: 24px; }}
  .header {{ background: linear-gradient(135deg, #1a3a5c, #2e7d62); color: #fff;
             padding: 28px 32px; border-radius: 12px; margin-bottom: 24px; }}
  .header h1 {{ font-size: 26px; font-weight: 700; }}
  .header p  {{ margin-top: 6px; opacity: .85; font-size: 13px; }}
  .card {{ background: #fff; border-radius: 10px; padding: 24px; margin-bottom: 20px;
           box-shadow: 0 2px 8px rgba(0,0,0,.08); }}
  .card h2 {{ font-size: 18px; color: #1a3a5c; border-bottom: 2px solid #2e7d62;
              padding-bottom: 8px; margin-bottom: 16px; }}
  .card h3 {{ font-size: 15px; color: #444; margin: 20px 0 10px; }}
  .img-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
               gap: 16px; }}
  .img-card {{ text-align: center; }}
  .img-card img {{ width: 100%; border-radius: 6px; border: 1px solid #ddd; }}
  .img-card p {{ margin-top: 6px; font-size: 12px; color: #666; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ background: #1a3a5c; color: #fff; padding: 10px 12px; text-align: left; }}
  td {{ padding: 9px 12px; border-bottom: 1px solid #eee; }}
  tr:hover td {{ background: #f7faf9; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 10px;
            color: #fff; font-size: 11px; font-weight: 600; }}
  .stat-row {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
               gap: 12px; margin-bottom: 16px; }}
  .stat-box {{ background: #f7faf9; border: 1px solid #dde; border-radius: 8px;
               padding: 14px; text-align: center; }}
  .stat-val {{ font-size: 22px; font-weight: 700; color: #1a3a5c; }}
  .stat-lbl {{ font-size: 11px; color: #888; margin-top: 4px; }}
  .file-block {{ border-left: 4px solid #2e7d62; padding-left: 16px; margin-bottom: 32px; }}
  .file-block h2 {{ color: #2e7d62; font-size: 17px; margin-bottom: 12px; }}
  .section-divider {{ border: none; border-top: 1px solid #e0e0e0; margin: 24px 0; }}
  .toc {{ background: #f7faf9; border: 1px solid #dde; border-radius: 8px;
          padding: 14px 20px; margin-bottom: 24px; }}
  .toc h3 {{ margin-bottom: 8px; color: #444; font-size: 14px; }}
  .toc ul {{ list-style: none; padding: 0; }}
  .toc li {{ padding: 2px 0; }}
  .toc a  {{ color: #2e7d62; text-decoration: none; font-size: 13px; }}
  .toc a:hover {{ text-decoration: underline; }}
  footer {{ text-align: center; padding: 20px; color: #999; font-size: 12px; }}
</style>
</head>
<body>
<div class="container">
"""

_HTML_FOOT = """
<footer>
  Generated by HyperspectralPipeline &nbsp;|&nbsp; {timestamp}
</footer>
</div></body></html>
"""


# ===================================================================
# Reporter class
# ===================================================================

class Reporter:
    """Accumulate per-file results and render a final HTML report."""

    def __init__(self, config: dict):
        self.cfg = config
        self.rcfg = config.get("report", {})
        self.results: List[Dict[str, Any]] = []

    # ---------------------------------------------------------- #
    # Public
    # ---------------------------------------------------------- #

    def add_result(
        self,
        filename: str,
        data: np.ndarray,
        class_map: np.ndarray,
        class_info: List[Dict[str, Any]],
        spectra: List[Dict[str, Any]],
        wavelengths: Optional[List[float]],
        metadata: Dict[str, Any],
    ) -> None:
        self.results.append(
            dict(
                filename=filename,
                data=data,
                class_map=class_map,
                class_info=class_info,
                spectra=spectra,
                wavelengths=wavelengths,
                metadata=metadata,
            )
        )

    def render(self, output_path: str | Path) -> None:
        """Write the complete HTML report to *output_path*."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        title = self.rcfg.get("title", "Hyperspectral Analysis Report")
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        html_parts = [
            _HTML_HEAD.format(title=title),
            f'<div class="header"><h1>{title}</h1>'
            f'<p>생성 시각: {timestamp} &nbsp;|&nbsp; '
            f'처리 파일 수: {len(self.results)}</p></div>',
        ]

        # Table of contents
        toc_items = "\n".join(
            f'<li><a href="#file-{i}">{r["filename"]}</a></li>'
            for i, r in enumerate(self.results)
        )
        html_parts.append(
            f'<div class="toc"><h3>목차</h3><ul>{toc_items}</ul></div>'
        )

        for i, result in enumerate(self.results):
            html_parts.append(self._render_file_block(i, result))

        html_parts.append(_HTML_FOOT.format(timestamp=timestamp))
        html = "\n".join(html_parts)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        logger.info(f"Report saved: {output_path}")

    # ---------------------------------------------------------- #
    # Per-file block
    # ---------------------------------------------------------- #

    def _render_file_block(self, idx: int, result: Dict[str, Any]) -> str:
        fname    = result["filename"]
        data     = result["data"]
        class_map = result["class_map"]
        class_info = result["class_info"]
        spectra  = result["spectra"]
        wl       = result["wavelengths"]
        meta     = result["metadata"]

        H, W, B = data.shape
        n_px     = H * W

        parts = [
            f'<div class="file-block" id="file-{idx}">',
            f'<h2>📁 {fname}</h2>',

            # Quick stats
            '<div class="stat-row">',
            self._stat_box("해상도", f"{W} × {H}"),
            self._stat_box("밴드 수", str(B)),
            self._stat_box("총 픽셀", f"{n_px:,}"),
            self._stat_box("형식", meta.get("format", "—")),
            '</div>',

            # Image composites + classification map
            '<div class="card">',
            '<h2>이미지 시각화</h2>',
            '<div class="img-grid">',
            self._img_card("RGB 합성", self._make_rgb(data, wl, "rgb")),
            self._img_card("CIR 위색도 (NIR-R-G)", self._make_rgb(data, wl, "cir")),
            self._img_card("분류 결과", self._make_class_map_img(class_map, class_info)),
            '</div></div>',

            # Classification summary table
            '<div class="card">',
            '<h2>분류 요약</h2>',
            self._class_table(class_info, n_px),
            '</div>',

            # Spectral plots
            '<div class="card">',
            '<h2>클래스별 반사율 스펙트럼</h2>',
            self._spectra_plot_html(spectra, wl),
            '</div>',

            '</div>',  # file-block
        ]
        return "\n".join(parts)

    # ---------------------------------------------------------- #
    # Image helpers
    # ---------------------------------------------------------- #

    def _make_rgb(
        self,
        data: np.ndarray,
        wavelengths: Optional[List[float]],
        mode: str = "rgb",
    ) -> str:
        """Render RGB or CIR composite, return base64 PNG string."""
        rcfg = self.rcfg
        H, W, B = data.shape

        if mode == "rgb":
            targets = [
                rcfg.get("rgb_red_nm",   660),
                rcfg.get("rgb_green_nm", 550),
                rcfg.get("rgb_blue_nm",  450),
            ]
        else:  # CIR: NIR / Red / Green
            targets = [800, 660, 550]

        channels = []
        for t in targets:
            if wavelengths:
                wl = np.array(wavelengths)
                idx = int(np.argmin(np.abs(wl - t)))
            else:
                frac = (t - 400) / 600.0   # rough guess 400–1000nm
                idx = int(np.clip(frac * (B - 1), 0, B - 1))
            channels.append(data[:, :, idx])

        rgb = np.stack(channels, axis=2)
        lo, hi = rcfg.get("rgb_percentile_stretch", [2, 98])
        for c in range(3):
            p_lo = np.percentile(rgb[:, :, c], lo)
            p_hi = np.percentile(rgb[:, :, c], hi)
            if p_hi > p_lo:
                rgb[:, :, c] = (rgb[:, :, c] - p_lo) / (p_hi - p_lo)
        rgb = np.clip(rgb, 0, 1)

        return self._array_to_b64(rgb)

    def _make_class_map_img(
        self,
        class_map: np.ndarray,
        class_info: List[Dict[str, Any]],
    ) -> str:
        H, W = class_map.shape
        rgb = np.zeros((H, W, 3), dtype=np.uint8)
        for cinfo in class_info:
            mask = class_map == cinfo["id"]
            rgb[mask] = cinfo["color"]
        return self._array_to_b64(rgb.astype(np.float32) / 255.0)

    @staticmethod
    def _array_to_b64(arr: np.ndarray) -> str:
        """Convert (H, W, 3) float [0,1] array to base64 PNG."""
        fig, ax = plt.subplots(figsize=(5, 5), dpi=100)
        ax.imshow(arr)
        ax.axis("off")
        fig.tight_layout(pad=0)
        buf = io.BytesIO()
        fig.savefig(buf, format="png", bbox_inches="tight", pad_inches=0, dpi=100)
        plt.close(fig)
        buf.seek(0)
        return base64.b64encode(buf.read()).decode("ascii")

    @staticmethod
    def _img_card(title: str, b64: str) -> str:
        return (
            f'<div class="img-card">'
            f'<img src="data:image/png;base64,{b64}" alt="{title}">'
            f'<p>{title}</p></div>'
        )

    # ---------------------------------------------------------- #
    # Table helper
    # ---------------------------------------------------------- #

    def _class_table(
        self,
        class_info: List[Dict[str, Any]],
        total_px: int,
    ) -> str:
        rows = ""
        for c in sorted(class_info, key=lambda x: -x["n_pixels"]):
            r, g, b_ = c["color"]
            badge = (
                f'<span class="badge" style="background:rgb({r},{g},{b_})">'
                f'{c["name"]}</span>'
            )
            pct = 100.0 * c["n_pixels"] / total_px
            rows += (
                f'<tr><td>{badge}</td>'
                f'<td>{c["id"]}</td>'
                f'<td>{c["n_pixels"]:,}</td>'
                f'<td>{pct:.2f}%</td></tr>'
            )
        return (
            "<table>"
            "<thead><tr><th>클래스</th><th>ID</th><th>픽셀 수</th><th>비율</th></tr></thead>"
            f"<tbody>{rows}</tbody></table>"
        )

    # ---------------------------------------------------------- #
    # Plotly spectral chart
    # ---------------------------------------------------------- #

    def _spectra_plot_html(
        self,
        spectra: List[Dict[str, Any]],
        wavelengths: Optional[List[float]],
    ) -> str:
        try:
            import plotly.graph_objects as go
        except ImportError:
            return "<p><em>plotly를 설치하면 인터랙티브 차트가 표시됩니다: pip install plotly</em></p>"

        show_std    = self.rcfg.get("spectra_show_std", True)
        show_minmax = self.rcfg.get("spectra_show_minmax", False)

        fig = go.Figure()
        for s in spectra:
            name  = s["name"]
            r, g, b_ = s["color"]
            color_rgb = f"rgb({r},{g},{b_})"

            wl = s.get("wavelengths") or list(range(len(s["mean"])))
            mean = s["mean"]
            std  = s["std"]

            # Mean line
            fig.add_trace(go.Scatter(
                x=wl, y=mean.tolist(),
                name=name,
                mode="lines",
                line=dict(color=color_rgb, width=2),
            ))

            # ±1 std envelope
            if show_std:
                upper = (mean + std).tolist()
                lower = (mean - std).tolist()
                fig.add_trace(go.Scatter(
                    x=wl + wl[::-1],
                    y=upper + lower[::-1],
                    fill="toself",
                    fillcolor=f"rgba({r},{g},{b_},0.15)",
                    line=dict(color="rgba(255,255,255,0)"),
                    name=f"{name} ±std",
                    showlegend=False,
                ))

        x_label = "파장 (nm)" if wavelengths else "밴드 인덱스"
        fig.update_layout(
            xaxis_title=x_label,
            yaxis_title="반사율",
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
            margin=dict(l=50, r=20, t=40, b=50),
            hovermode="x unified",
            height=420,
            plot_bgcolor="#fafafa",
            paper_bgcolor="#ffffff",
        )

        div_html = fig.to_html(full_html=False, include_plotlyjs=False)
        return div_html

    # ---------------------------------------------------------- #
    # Utility
    # ---------------------------------------------------------- #

    @staticmethod
    def _stat_box(label: str, value: str) -> str:
        return (
            f'<div class="stat-box">'
            f'<div class="stat-val">{value}</div>'
            f'<div class="stat-lbl">{label}</div>'
            f'</div>'
        )
